### ISSUE TITLE
Crash when attempting to talk to Bailey on testing server

### ISSUE THREAD

**Issue by frodare** [ToroCraft/Dailies#41]
[05:59:30] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_71]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_71]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at net.torocraft.dailies.BaileyInventory.func_174888_l(BaileyInventory.java:154) ~[BaileyInventory.class:?]
	at net.torocraft.dailies.BaileyInventory.<init>(BaileyInventory.java:36) ~[BaileyInventory.class:?]
	at net.torocraft.dailies.gui.DailiesGuiHandler.getServerGuiElement(DailiesGuiHandler.java:17) ~[DailiesGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:254) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:89) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2498) ~[aay.class:?]
	at net.torocraft.dailies.entities.EntityBailey.func_184645_a(EntityBailey.java:60) ~[EntityBailey.class:?]
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1213) ~[sx.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1185) ~[aay.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1017) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[ix.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[ix.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_71]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_71]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_71]
	at net.torocraft.dailies.BaileyInventory.func_174888_l(BaileyInventory.java:154) ~[BaileyInventory.class:?]
	at net.torocraft.dailies.BaileyInventory.<init>(BaileyInventory.java:36) ~[BaileyInventory.class:?]
	at net.torocraft.dailies.gui.DailiesGuiHandler.getServerGuiElement(DailiesGuiHandler.java:17) ~[DailiesGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:254) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:89) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2498) ~[aay.class:?]
	at net.torocraft.dailies.entities.EntityBailey.func_184645_a(EntityBailey.java:60) ~[EntityBailey.class:?]
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1213) ~[sx.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1185) ~[aay.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1017) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[ix.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[ix.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_71]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.NullPointerException

**Comment by zeriley** [comment]
In BaileyInventory.java, this import:
import scala.actors.threadpool.Arrays;

just needs to be replaced by this import:
import java.util.Arrays;

I don't know why it defaulted to a scala import, and why it worked on a single player server, but not a multiplayer one. 

I'll fix that when I get home tonight, unless someone beats me to it.

**Comment by pandapaul** [comment]
@zeriley rockin
